
-- explore magnitudes

-- ##############################

-- find total number of customers by countries

-- ##############################

select
	country,
	COUNT(distinct customer_id) as total_customers
	from [gold.dim_customers]
	group by country
	order by total_customers;

-- ##############################

-- find total number of customers by genders

-- ##############################

select 
	gender,
	COUNT(distinct customer_id) as total_customers
	from [gold.dim_customers]
	group by gender
	order by total_customers;

-- ##############################

-- find total number of products by category

-- ##############################

select 
	category,
	COUNT(distinct product_id) as total_products
	from [gold.dim_products]
	group by category
	order by total_products;

-- ##############################

-- what is average cost in each category

-- ##############################

select 
	p.category,
	avg(s.sales_amount) as total_sales
	from [gold.fact_sales] s
	join [gold.dim_products] p 
	on s.product_key = p.product_id
	group by p.category
	order by total_sales;

-- ##############################

-- what is total revenue generated by each category

-- ##############################

select 
	p.category,
	SUM(s.sales_amount) as total_revenue
	from [gold.fact_sales] s
	left join [gold.dim_products] p 
	on s.product_key = p.product_key
	group by p.category
	order by total_revenue desc;



-- ##############################

-- what is total revenue generated by each customers

-- ##############################

select 
	c.customer_key,
    c.first_name,
	c.last_name,
	SUM(s.sales_amount) as total_revenue
	from [gold.fact_sales] s
	left join [gold.dim_customers] c 
	on s.customer_key = c.customer_id
	where c.customer_id is not null
	group by c.customer_key ,c.first_name,c.last_name
	order by total_revenue desc;


-- ##############################

-- what is the distribution of items sold across countries

-- ##############################


select 
	c.country,
	SUM(s.quantity) as total_sold_items
	from [gold.fact_sales] s
	left join [gold.dim_customers] c 
	on s.customer_key = c.customer_id
	where c.customer_id is not null
	group by c.country
	order by total_sold_items desc;